code --install-extension aaron-bond.better-comments
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension denoland.vscode-deno
code --install-extension eamodio.gitlens
code --install-extension enkia.tokyo-night
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension matklad.rust-analyzer
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension PKief.material-icon-theme
code --install-extension ritwickdey.live-sass
code --install-extension ritwickdey.LiveServer
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension statiolake.vscode-rustfmt
code --install-extension teabyii.ayu
code --install-extension thenikso.github-plus-theme
code --install-extension treetrum.statusbar-format-on-save
code --install-extension yzhang.markdown-all-in-one
