code --install-extension aaron-bond.better-comments
code --install-extension BendixMa.dart-data-class-generator
code --install-extension bungcip.better-toml
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension denoland.vscode-deno
code --install-extension eamodio.gitlens
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension golang.go
code --install-extension matklad.rust-analyzer
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension octref.vetur
code --install-extension PKief.material-icon-theme
code --install-extension ritwickdey.live-sass
code --install-extension ritwickdey.LiveServer
code --install-extension statiolake.vscode-rustfmt
code --install-extension teabyii.ayu
code --install-extension thenikso.github-plus-theme
